sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: o8rpgg2PzHlJhcvZWKb1kewodt+wf2YECG5n3vJpwCymEuMWAAP2as6yGiAu4vg+es/ZcDw64H+j7J86NfADaKsfj4y0nIsGSp1/yMr5ER8L/BCxqQuMTmJjlSCrFxYeUCarHW+sB2WQ3FIheYnpgS8iKsFl6NG+pBLfS85ru+pwd0FEEFRegbrj0L3IKmLX9vpzmRVM4wghXOXHUxq0JoEcgNPl4Ia03jOvIyo87Qv50nabttncFSHM0mNWgG3xsaicTjgzAimHcBNCxDDV0BHKPWqbRygT6uORQZYOgeVMockjzZ28taIAtl54PRz9vIV+hWQGLVFeL9jZKW89D2FmHOjJ8rKWcv/Cpsnlew26kLd7OM3iefHzKemU942+nNPzJ1E0R0wT591wQFdGcbN+fT1Mp0UJ+WwGpY6g+YSWccimTnQODMW6CQxLmwT06o0vCIf397rFqWmwL9nY9XGj+vu2mXkIN9eeZA+Boq6JZmDhO09shpJXjCvCzB3oqHO1r/SYjdNfNGDYUtBbnadW5XMC7MqUSeT4LruaEWymFrtlgA5UvQzp/GHLr4wG2Yun6x/mVQglzZw6yl5CCLAg+Jvk2ffEr1HC0gyhZEUDfzf3IzFACW7YKJKJXmS7uUREHeSv3wf64OdKsN32Uu0wLUkYjfYY05oycjO63EQ=

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

php:
  - 5.6
  - 7.1
  - 7.2

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=bin/dev-lib
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm install
  # Build the plugin for deployment
  - grunt 'Build the plugin.'

deploy:
  provider: releases
  api_key:
    secure: fZ0Z0wCCAiXbzGs3ysbcAxcjBxHchfgwP/UMzTFVeDC8odVvJj6hzH8ZqVhZbNUqvnOmSUhWdKKP7fn43ZSU9xHxIqYbEt8O7lIap4OOM2p42IjpqPLBT+D8cx67ss6sYuwAXSSIi2ydyHT1MQMxWchFLb4EAsuTsf3CNZdckykZ5bryDCJYWv2FENJ0IVwryxnTn35VHzv6Z1KcRlfJ0yXJ6pZeN4Ty6FV5sEdmD5sQ76RSliRgL6LXalaEU0Nl+pPAsn4zOekPWtNIpT/1WLnIg8TgRq/0wHzwKj1oATvaFTrGWQNwPZXb0nNSVIc5+kYGxKAhRwO3//UGNkTbjSdA9pqjh9WTHbRO/Z6016rBBYlaM+YcIuy67hyyiFfUeaxp5FwS8F0NmTDZDcOkSD5loC0U/N+e8HR0lGsp+0MgHfVeWyttWqG2P+lNRQpN2rSsd9z6znf9/O10EdcaTilbQXMGCgCP9adgBblPejCCeRFlX/IPANh/Pno5xvQH8iRD0W0eT4t/QACrLQyR8eLuTW1Lr+5QEZfddJHDLzkrYzmpGf4PgChGi4igipoEqKq/Cdz3Zy/duPB/fT6WFKwXFHD/fA5xemquGtLEvVxb2J2E/HXuBIfXWQMyl+4NolQi8uis8kUcNmeYsPJ/Kgsav6VO4n59QAQDbVQo2XM=
  file_glob: true
  file: build/webp-images-*.zip
  on:
    tags: true
    repo: CodeParrots/webp-images
    php: '7.2'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
